layout_spectrum: 0.9460371
color:
  saturation: 0.376054
  brandStrength: 0.2762052
  lightness: 0.9021922
  rhythmicContrast: 0.2445194
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.8052276
name: Robin Lodge Associates
